server:
  port: 8001
spring:
  application:
    name: com.nebula.iccp.security    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: mysql                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
    url: jdbc:mysql://127.0.0.1:3306/securitydb?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: Changeme_123
    driver-class-name: com.mysql.jdbc.Driver.
logging:
  level:
    root: INFO
